### ISSUE TITLE
CI pipeline

### ISSUE THREAD

**Issue by apirogov** [Materials-Data-Science-and-Informatics/awesome-fair-data#5]
* Fix the pipeline

* Make sure the linter works

* Do not disallow redirects in general (could be e.g. PURLs), maybe rather blacklist known URL shortener services

**Comment by broeder-j** [comment]
allowed links in commit 278416a51bdf54ccaff7d406ac16ad6339aad2b9

**Comment by broeder-j** [comment]
solved with commit 0701e92c1211fc4d96d9001b9739d0e00e75b3bf
